# Generated by Django 2.2.3 on 2019-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('unitPrice', models.FloatField(db_column='unit_price')),
                ('imageURL', models.CharField(db_column='image_url', max_length=1024)),
            ],
        ),
    ]
